// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\consul_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\consul_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_consul_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockConsulHandlerInterface is a mock of ConsulHandlerInterface interface.
type MockConsulHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConsulHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockConsulHandlerInterfaceMockRecorder is the mock recorder for MockConsulHandlerInterface.
type MockConsulHandlerInterfaceMockRecorder struct {
	mock *MockConsulHandlerInterface
}

// NewMockConsulHandlerInterface creates a new mock instance.
func NewMockConsulHandlerInterface(ctrl *gomock.Controller) *MockConsulHandlerInterface {
	mock := &MockConsulHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockConsulHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulHandlerInterface) EXPECT() *MockConsulHandlerInterfaceMockRecorder {
	return m.recorder
}

// GetConsulSecret mocks base method.
func (m *MockConsulHandlerInterface) GetConsulSecret(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConsulSecret", c)
}

// GetConsulSecret indicates an expected call of GetConsulSecret.
func (mr *MockConsulHandlerInterfaceMockRecorder) GetConsulSecret(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsulSecret", reflect.TypeOf((*MockConsulHandlerInterface)(nil).GetConsulSecret), c)
}
