// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\external_patient_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\external_patient_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_external_patient_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalPatientHandler is a mock of ExternalPatientHandler interface.
type MockExternalPatientHandler struct {
	ctrl     *gomock.Controller
	recorder *MockExternalPatientHandlerMockRecorder
	isgomock struct{}
}

// MockExternalPatientHandlerMockRecorder is the mock recorder for MockExternalPatientHandler.
type MockExternalPatientHandlerMockRecorder struct {
	mock *MockExternalPatientHandler
}

// NewMockExternalPatientHandler creates a new mock instance.
func NewMockExternalPatientHandler(ctrl *gomock.Controller) *MockExternalPatientHandler {
	mock := &MockExternalPatientHandler{ctrl: ctrl}
	mock.recorder = &MockExternalPatientHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalPatientHandler) EXPECT() *MockExternalPatientHandlerMockRecorder {
	return m.recorder
}

// CreateExternalPatient mocks base method.
func (m *MockExternalPatientHandler) CreateExternalPatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateExternalPatient", c)
}

// CreateExternalPatient indicates an expected call of CreateExternalPatient.
func (mr *MockExternalPatientHandlerMockRecorder) CreateExternalPatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalPatient", reflect.TypeOf((*MockExternalPatientHandler)(nil).CreateExternalPatient), c)
}

// GetExternalPatientByID mocks base method.
func (m *MockExternalPatientHandler) GetExternalPatientByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetExternalPatientByID", c)
}

// GetExternalPatientByID indicates an expected call of GetExternalPatientByID.
func (mr *MockExternalPatientHandlerMockRecorder) GetExternalPatientByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByID", reflect.TypeOf((*MockExternalPatientHandler)(nil).GetExternalPatientByID), c)
}

// GetExternalPatientByIDCached mocks base method.
func (m *MockExternalPatientHandler) GetExternalPatientByIDCached(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetExternalPatientByIDCached", c)
}

// GetExternalPatientByIDCached indicates an expected call of GetExternalPatientByIDCached.
func (mr *MockExternalPatientHandlerMockRecorder) GetExternalPatientByIDCached(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByIDCached", reflect.TypeOf((*MockExternalPatientHandler)(nil).GetExternalPatientByIDCached), c)
}

// GetExternalPatientByIDDelayed mocks base method.
func (m *MockExternalPatientHandler) GetExternalPatientByIDDelayed(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetExternalPatientByIDDelayed", c)
}

// GetExternalPatientByIDDelayed indicates an expected call of GetExternalPatientByIDDelayed.
func (mr *MockExternalPatientHandlerMockRecorder) GetExternalPatientByIDDelayed(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByIDDelayed", reflect.TypeOf((*MockExternalPatientHandler)(nil).GetExternalPatientByIDDelayed), c)
}

// SearchExternalPatients mocks base method.
func (m *MockExternalPatientHandler) SearchExternalPatients(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SearchExternalPatients", c)
}

// SearchExternalPatients indicates an expected call of SearchExternalPatients.
func (mr *MockExternalPatientHandlerMockRecorder) SearchExternalPatients(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchExternalPatients", reflect.TypeOf((*MockExternalPatientHandler)(nil).SearchExternalPatients), c)
}
