// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\vault_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\vault_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_vault_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockVaultHandlerInterface is a mock of VaultHandlerInterface interface.
type MockVaultHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVaultHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockVaultHandlerInterfaceMockRecorder is the mock recorder for MockVaultHandlerInterface.
type MockVaultHandlerInterfaceMockRecorder struct {
	mock *MockVaultHandlerInterface
}

// NewMockVaultHandlerInterface creates a new mock instance.
func NewMockVaultHandlerInterface(ctrl *gomock.Controller) *MockVaultHandlerInterface {
	mock := &MockVaultHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockVaultHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultHandlerInterface) EXPECT() *MockVaultHandlerInterfaceMockRecorder {
	return m.recorder
}

// GetVaultSecret mocks base method.
func (m *MockVaultHandlerInterface) GetVaultSecret(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetVaultSecret", c)
}

// GetVaultSecret indicates an expected call of GetVaultSecret.
func (mr *MockVaultHandlerInterfaceMockRecorder) GetVaultSecret(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaultSecret", reflect.TypeOf((*MockVaultHandlerInterface)(nil).GetVaultSecret), c)
}
