// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\vault_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\vault_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_vault_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockVaultHandler is a mock of *VaultHandler interface.
type MockVaultHandler struct {
	ctrl     *gomock.Controller
	recorder *MockVaultHandlerMockRecorder
	isgomock struct{}
}

// MockVaultHandlerMockRecorder is the mock recorder for MockVaultHandler.
type MockVaultHandlerMockRecorder struct {
	mock *MockVaultHandler
}

// NewMockVaultHandler creates a new mock instance.
func NewMockVaultHandler(ctrl *gomock.Controller) *MockVaultHandler {
	mock := &MockVaultHandler{ctrl: ctrl}
	mock.recorder = &MockVaultHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultHandler) EXPECT() *MockVaultHandlerMockRecorder {
	return m.recorder
}

// GetVaultSecret mocks base method.
func (m *MockVaultHandler) GetVaultSecret(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetVaultSecret", c)
}

// GetVaultSecret indicates an expected call of GetVaultSecret.
func (mr *MockVaultHandlerMockRecorder) GetVaultSecret(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaultSecret", reflect.TypeOf((*MockVaultHandler)(nil).GetVaultSecret), c)
}
