// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\consul_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\consul_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_consul_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockConsulHandler is a mock of *ConsulHandler interface.
type MockConsulHandler struct {
	ctrl     *gomock.Controller
	recorder *MockConsulHandlerMockRecorder
	isgomock struct{}
}

// MockConsulHandlerMockRecorder is the mock recorder for MockConsulHandler.
type MockConsulHandlerMockRecorder struct {
	mock *MockConsulHandler
}

// NewMockConsulHandler creates a new mock instance.
func NewMockConsulHandler(ctrl *gomock.Controller) *MockConsulHandler {
	mock := &MockConsulHandler{ctrl: ctrl}
	mock.recorder = &MockConsulHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulHandler) EXPECT() *MockConsulHandlerMockRecorder {
	return m.recorder
}

// GetConsulSecret mocks base method.
func (m *MockConsulHandler) GetConsulSecret(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetConsulSecret", c)
}

// GetConsulSecret indicates an expected call of GetConsulSecret.
func (mr *MockConsulHandlerMockRecorder) GetConsulSecret(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsulSecret", reflect.TypeOf((*MockConsulHandler)(nil).GetConsulSecret), c)
}
