// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\external_patient_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\external_patient_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_external_patient_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalPatientHandlerInterface is a mock of ExternalPatientHandlerInterface interface.
type MockExternalPatientHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExternalPatientHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockExternalPatientHandlerInterfaceMockRecorder is the mock recorder for MockExternalPatientHandlerInterface.
type MockExternalPatientHandlerInterfaceMockRecorder struct {
	mock *MockExternalPatientHandlerInterface
}

// NewMockExternalPatientHandlerInterface creates a new mock instance.
func NewMockExternalPatientHandlerInterface(ctrl *gomock.Controller) *MockExternalPatientHandlerInterface {
	mock := &MockExternalPatientHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockExternalPatientHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalPatientHandlerInterface) EXPECT() *MockExternalPatientHandlerInterfaceMockRecorder {
	return m.recorder
}

// GetExternalPatientByID mocks base method.
func (m *MockExternalPatientHandlerInterface) GetExternalPatientByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetExternalPatientByID", c)
}

// GetExternalPatientByID indicates an expected call of GetExternalPatientByID.
func (mr *MockExternalPatientHandlerInterfaceMockRecorder) GetExternalPatientByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByID", reflect.TypeOf((*MockExternalPatientHandlerInterface)(nil).GetExternalPatientByID), c)
}

// SearchExternalPatients mocks base method.
func (m *MockExternalPatientHandlerInterface) SearchExternalPatients(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SearchExternalPatients", c)
}

// SearchExternalPatients indicates an expected call of SearchExternalPatients.
func (mr *MockExternalPatientHandlerInterfaceMockRecorder) SearchExternalPatients(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchExternalPatients", reflect.TypeOf((*MockExternalPatientHandlerInterface)(nil).SearchExternalPatients), c)
}
