// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\patient_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\patient_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\mocks\mock_patient_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPatientHandler is a mock of *PatientHandler interface.
type MockPatientHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPatientHandlerMockRecorder
	isgomock struct{}
}

// MockPatientHandlerMockRecorder is the mock recorder for MockPatientHandler.
type MockPatientHandlerMockRecorder struct {
	mock *MockPatientHandler
}

// NewMockPatientHandler creates a new mock instance.
func NewMockPatientHandler(ctrl *gomock.Controller) *MockPatientHandler {
	mock := &MockPatientHandler{ctrl: ctrl}
	mock.recorder = &MockPatientHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientHandler) EXPECT() *MockPatientHandlerMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockPatientHandler) CreatePatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreatePatient", c)
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientHandlerMockRecorder) CreatePatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientHandler)(nil).CreatePatient), c)
}

// DeletePatient mocks base method.
func (m *MockPatientHandler) DeletePatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeletePatient", c)
}

// DeletePatient indicates an expected call of DeletePatient.
func (mr *MockPatientHandlerMockRecorder) DeletePatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePatient", reflect.TypeOf((*MockPatientHandler)(nil).DeletePatient), c)
}

// GetPatient mocks base method.
func (m *MockPatientHandler) GetPatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPatient", c)
}

// GetPatient indicates an expected call of GetPatient.
func (mr *MockPatientHandlerMockRecorder) GetPatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatient", reflect.TypeOf((*MockPatientHandler)(nil).GetPatient), c)
}

// GetPatients mocks base method.
func (m *MockPatientHandler) GetPatients(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPatients", c)
}

// GetPatients indicates an expected call of GetPatients.
func (mr *MockPatientHandlerMockRecorder) GetPatients(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatients", reflect.TypeOf((*MockPatientHandler)(nil).GetPatients), c)
}

// PatchPatient mocks base method.
func (m *MockPatientHandler) PatchPatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PatchPatient", c)
}

// PatchPatient indicates an expected call of PatchPatient.
func (mr *MockPatientHandlerMockRecorder) PatchPatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPatient", reflect.TypeOf((*MockPatientHandler)(nil).PatchPatient), c)
}

// UpdatePatient mocks base method.
func (m *MockPatientHandler) UpdatePatient(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePatient", c)
}

// UpdatePatient indicates an expected call of UpdatePatient.
func (mr *MockPatientHandlerMockRecorder) UpdatePatient(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatient", reflect.TypeOf((*MockPatientHandler)(nil).UpdatePatient), c)
}
