// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\domain\external_patient.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\domain\external_patient.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\domain\mocks\mock_external_patient.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	fhir "github.com/samply/golang-fhir-models/fhir-models/fhir"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalPatientService is a mock of ExternalPatientService interface.
type MockExternalPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockExternalPatientServiceMockRecorder
	isgomock struct{}
}

// MockExternalPatientServiceMockRecorder is the mock recorder for MockExternalPatientService.
type MockExternalPatientServiceMockRecorder struct {
	mock *MockExternalPatientService
}

// NewMockExternalPatientService creates a new mock instance.
func NewMockExternalPatientService(ctrl *gomock.Controller) *MockExternalPatientService {
	mock := &MockExternalPatientService{ctrl: ctrl}
	mock.recorder = &MockExternalPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalPatientService) EXPECT() *MockExternalPatientServiceMockRecorder {
	return m.recorder
}

// CreateExternalPatient mocks base method.
func (m *MockExternalPatientService) CreateExternalPatient(patient *fhir.Patient) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExternalPatient", patient)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternalPatient indicates an expected call of CreateExternalPatient.
func (mr *MockExternalPatientServiceMockRecorder) CreateExternalPatient(patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalPatient", reflect.TypeOf((*MockExternalPatientService)(nil).CreateExternalPatient), patient)
}

// GetExternalPatientByID mocks base method.
func (m *MockExternalPatientService) GetExternalPatientByID(id string) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalPatientByID", id)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalPatientByID indicates an expected call of GetExternalPatientByID.
func (mr *MockExternalPatientServiceMockRecorder) GetExternalPatientByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByID", reflect.TypeOf((*MockExternalPatientService)(nil).GetExternalPatientByID), id)
}

// GetExternalPatientByIDDelayed mocks base method.
func (m *MockExternalPatientService) GetExternalPatientByIDDelayed(ctx context.Context, id string, timeout time.Duration) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalPatientByIDDelayed", ctx, id, timeout)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalPatientByIDDelayed indicates an expected call of GetExternalPatientByIDDelayed.
func (mr *MockExternalPatientServiceMockRecorder) GetExternalPatientByIDDelayed(ctx, id, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByIDDelayed", reflect.TypeOf((*MockExternalPatientService)(nil).GetExternalPatientByIDDelayed), ctx, id, timeout)
}

// SearchExternalPatients mocks base method.
func (m *MockExternalPatientService) SearchExternalPatients(params map[string]string) (*fhir.Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchExternalPatients", params)
	ret0, _ := ret[0].(*fhir.Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchExternalPatients indicates an expected call of SearchExternalPatients.
func (mr *MockExternalPatientServiceMockRecorder) SearchExternalPatients(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchExternalPatients", reflect.TypeOf((*MockExternalPatientService)(nil).SearchExternalPatients), params)
}
