version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fhir_postgres
    environment:
      POSTGRES_DB: fhir_demo
      POSTGRES_USER: fhir_user
      POSTGRES_PASSWORD: fhir_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fhir_user -d fhir_demo"]
      interval: 30s
      timeout: 10s
      retries: 3

  fhir-api:
    build: .
    container_name: fhir_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fhir_user
      DB_PASSWORD: fhir_password
      DB_NAME: fhir_demo
      DB_SSLMODE: disable
      SERVER_PORT: 8080
      GIN_MODE: release
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/root/logs

volumes:
  postgres_data:
