version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fhir_postgres
    environment:
      POSTGRES_DB: fhir_demo
      POSTGRES_USER: fhir_user
      POSTGRES_PASSWORD: fhir_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fhir_user -d fhir_demo"]
      interval: 30s
      timeout: 10s
      retries: 3

  consul:
    image: hashicorp/consul:1.21.0
    container_name: fhir_consul
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect 1 -client=0.0.0.0 -ui -data-dir=/consul/data"
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_DATA_DIR: /consul/data
    volumes:
      - consul_data:/consul/data
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

  fhir-api:
    build: .
    container_name: fhir_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fhir_user
      DB_PASSWORD: fhir_password
      DB_NAME: fhir_demo
      DB_SSLMODE: disable
      SERVER_PORT: 8080
      GIN_MODE: release
      LOG_LEVEL: info
      CONSUL_ADDRESS: http://consul:8500
      CONSUL_KEY: myapp/secret
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started
    volumes:
      - ./logs:/root/logs

volumes:
  postgres_data:
  consul_data:
