// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\pkg\fhirclient\client.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\pkg\fhirclient\client.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\pkg\fhirclient\mocks\mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	fhir "github.com/samply/golang-fhir-models/fhir-models/fhir"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of *Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockClient) CreatePatient(ctx context.Context, patient *fhir.Patient) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", ctx, patient)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockClientMockRecorder) CreatePatient(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockClient)(nil).CreatePatient), ctx, patient)
}

// GetPatientByID mocks base method.
func (m *MockClient) GetPatientByID(ctx context.Context, id string) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientByID", ctx, id)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientByID indicates an expected call of GetPatientByID.
func (mr *MockClientMockRecorder) GetPatientByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientByID", reflect.TypeOf((*MockClient)(nil).GetPatientByID), ctx, id)
}

// SearchPatients mocks base method.
func (m *MockClient) SearchPatients(ctx context.Context, queryParams map[string]string) (*fhir.Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPatients", ctx, queryParams)
	ret0, _ := ret[0].(*fhir.Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPatients indicates an expected call of SearchPatients.
func (mr *MockClientMockRecorder) SearchPatients(ctx, queryParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPatients", reflect.TypeOf((*MockClient)(nil).SearchPatients), ctx, queryParams)
}
