// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\service\external_patient_service.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\service\external_patient_service.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\service\mocks\mock_external_patient_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	fhir "github.com/samply/golang-fhir-models/fhir-models/fhir"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalPatientService is a mock of ExternalPatientService interface.
type MockExternalPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockExternalPatientServiceMockRecorder
	isgomock struct{}
}

// MockExternalPatientServiceMockRecorder is the mock recorder for MockExternalPatientService.
type MockExternalPatientServiceMockRecorder struct {
	mock *MockExternalPatientService
}

// NewMockExternalPatientService creates a new mock instance.
func NewMockExternalPatientService(ctrl *gomock.Controller) *MockExternalPatientService {
	mock := &MockExternalPatientService{ctrl: ctrl}
	mock.recorder = &MockExternalPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalPatientService) EXPECT() *MockExternalPatientServiceMockRecorder {
	return m.recorder
}

// CreateExternalPatient mocks base method.
func (m *MockExternalPatientService) CreateExternalPatient(ctx context.Context, patient *fhir.Patient) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExternalPatient", ctx, patient)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExternalPatient indicates an expected call of CreateExternalPatient.
func (mr *MockExternalPatientServiceMockRecorder) CreateExternalPatient(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalPatient", reflect.TypeOf((*MockExternalPatientService)(nil).CreateExternalPatient), ctx, patient)
}

// GetExternalPatientByID mocks base method.
func (m *MockExternalPatientService) GetExternalPatientByID(ctx context.Context, id string) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalPatientByID", ctx, id)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalPatientByID indicates an expected call of GetExternalPatientByID.
func (mr *MockExternalPatientServiceMockRecorder) GetExternalPatientByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalPatientByID", reflect.TypeOf((*MockExternalPatientService)(nil).GetExternalPatientByID), ctx, id)
}

// GetPatientCached mocks base method.
func (m *MockExternalPatientService) GetPatientCached(ctx context.Context, id string) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientCached", ctx, id)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientCached indicates an expected call of GetPatientCached.
func (mr *MockExternalPatientServiceMockRecorder) GetPatientCached(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientCached", reflect.TypeOf((*MockExternalPatientService)(nil).GetPatientCached), ctx, id)
}

// GetPatientDelayed mocks base method.
func (m *MockExternalPatientService) GetPatientDelayed(ctx context.Context, id string, timeout time.Duration) (*fhir.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientDelayed", ctx, id, timeout)
	ret0, _ := ret[0].(*fhir.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientDelayed indicates an expected call of GetPatientDelayed.
func (mr *MockExternalPatientServiceMockRecorder) GetPatientDelayed(ctx, id, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientDelayed", reflect.TypeOf((*MockExternalPatientService)(nil).GetPatientDelayed), ctx, id, timeout)
}

// SearchExternalPatients mocks base method.
func (m *MockExternalPatientService) SearchExternalPatients(ctx context.Context, params map[string]string) (*fhir.Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchExternalPatients", ctx, params)
	ret0, _ := ret[0].(*fhir.Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchExternalPatients indicates an expected call of SearchExternalPatients.
func (mr *MockExternalPatientServiceMockRecorder) SearchExternalPatients(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchExternalPatients", reflect.TypeOf((*MockExternalPatientService)(nil).SearchExternalPatients), ctx, params)
}
