// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\routes\routes.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\routes\routes.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\routes\mocks\mock_routes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	handlers "go-fhir-demo/internal/api/handlers"
	cron "go-fhir-demo/internal/api/handlers/cron"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRouteSetup is a mock of *RouteSetup interface.
type MockRouteSetup struct {
	ctrl     *gomock.Controller
	recorder *MockRouteSetupMockRecorder
	isgomock struct{}
}

// MockRouteSetupMockRecorder is the mock recorder for MockRouteSetup.
type MockRouteSetupMockRecorder struct {
	mock *MockRouteSetup
}

// NewMockRouteSetup creates a new mock instance.
func NewMockRouteSetup(ctrl *gomock.Controller) *MockRouteSetup {
	mock := &MockRouteSetup{ctrl: ctrl}
	mock.recorder = &MockRouteSetupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteSetup) EXPECT() *MockRouteSetupMockRecorder {
	return m.recorder
}

// SetupRoutes mocks base method.
func (m *MockRouteSetup) SetupRoutes(patientHandler *handlers.PatientHandler, externalPatientHandler *handlers.ExternalPatientHandler, cronJobHandler cron.JobHandler, consulHandler ...*handlers.ConsulHandler) *gin.Engine {
	m.ctrl.T.Helper()
	varargs := []any{patientHandler, externalPatientHandler, cronJobHandler}
	for _, a := range consulHandler {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetupRoutes", varargs...)
	ret0, _ := ret[0].(*gin.Engine)
	return ret0
}

// SetupRoutes indicates an expected call of SetupRoutes.
func (mr *MockRouteSetupMockRecorder) SetupRoutes(patientHandler, externalPatientHandler, cronJobHandler any, consulHandler ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{patientHandler, externalPatientHandler, cronJobHandler}, consulHandler...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupRoutes", reflect.TypeOf((*MockRouteSetup)(nil).SetupRoutes), varargs...)
}
