// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\middleware\middleware.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\middleware\middleware.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\middleware\mocks\mock_middleware.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
