// Code generated by MockGen. DO NOT EDIT.
// Source: D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\cron\cronjob_handler.go
//
// Generated by this command:
//
//	mockgen -source=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\cron\cronjob_handler.go -destination=D:\Chinmay_Personal_Projects\Go_FHIR_Demo\internal\api\handlers\cron\mocks\mock_cronjob_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockCronJobHandler is a mock of *CronJobHandler interface.
type MockCronJobHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCronJobHandlerMockRecorder
	isgomock struct{}
}

// MockCronJobHandlerMockRecorder is the mock recorder for MockCronJobHandler.
type MockCronJobHandlerMockRecorder struct {
	mock *MockCronJobHandler
}

// NewMockCronJobHandler creates a new mock instance.
func NewMockCronJobHandler(ctrl *gomock.Controller) *MockCronJobHandler {
	mock := &MockCronJobHandler{ctrl: ctrl}
	mock.recorder = &MockCronJobHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronJobHandler) EXPECT() *MockCronJobHandlerMockRecorder {
	return m.recorder
}

// TriggerCleanupJob mocks base method.
func (m *MockCronJobHandler) TriggerCleanupJob(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerCleanupJob", c)
}

// TriggerCleanupJob indicates an expected call of TriggerCleanupJob.
func (mr *MockCronJobHandlerMockRecorder) TriggerCleanupJob(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerCleanupJob", reflect.TypeOf((*MockCronJobHandler)(nil).TriggerCleanupJob), c)
}

// TriggerDataSyncJob mocks base method.
func (m *MockCronJobHandler) TriggerDataSyncJob(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerDataSyncJob", c)
}

// TriggerDataSyncJob indicates an expected call of TriggerDataSyncJob.
func (mr *MockCronJobHandlerMockRecorder) TriggerDataSyncJob(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerDataSyncJob", reflect.TypeOf((*MockCronJobHandler)(nil).TriggerDataSyncJob), c)
}
